### PR TITLE
Incompatibility exposed with interaction of varArgs and any

### PR DESCRIPTION
**Pull request by luke-gumbley**
This particular case wasn't covered by any tests in typed-function for it so it slipped past. See first commit for the failing case.

This PR is a WIP for now, just to let you know this is why there's a failing math.mode test in mathjs... Should be finished tomorrow. Last part should be fixing the call signature for varArgs sigs in Node.toCode. Sorry!

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for your quick reply on https://github.com/josdejong/mathjs/issues/477. Things can happen, even with heavily unit tested libraries. 

Only right now a lot of the unit tests of `typed-function` are failing on [Travis](https://travis-ci.org/josdejong/typed-function), it's probably something small, so I can't yet merge your PR. I hope to have a look into this tonight.

**Comment by josdejong** [comment]
I have not enough time tonight to figure this out. Since you're in the middle of it I will await your fix. (and in the worst case we can just release a v0.10.3 which reverts the fix of v0.10.2, and take the time to create a fix for both issues).

**Comment by josdejong** [comment]
@luke-gumbley I've reverted your fix of v0.10.2 for the time being, so we have stable tests for math.js again and can take the time to fix using multiple `any` types in a signature again _and_ the variable args issue. I've added unit tests for the latter, and skipped the unit test for multiple `any` (added a FIXME there).

You can grab your fix of v0.10.2 again via the version tag: https://github.com/josdejong/typed-function/tree/v0.10.2

**Comment by luke-gumbley** [comment]
Totally sensible. Thanks Jos! Sorry I missed the issue... fixing has meant I have to go a bit deeper than I really wanted to in a single PR but I'll get there.

**Comment by josdejong** [comment]
No problem, thanks that you want to really solve this. Please be critical on the code of typed-function, it's a first iteration and I have a feeling that things could/should be much simpler then they currently are. If you have suggestions to improve the code please let me know.

**Comment by josdejong** [comment]
It has been a while, but I've finally fixed this issue of not being able to use `any` in multi-layered paths.

I've fixed it by letting signatures for which there is an alternative signature (with `any` anywhere in the path) falling through to to this signature instead of throwing an exception or expanding all alternative signatures with `any` in the current leaf of the tree.

**Pull request closed without merging**
