### PR TITLE
Set function length to max params (Fixes #13)

### LINKED ISSUE #13: Function length
Hello!

I just came back to an old project that was using typed-function internally and tried to update to the latest version.  Unfortunately, I've found that the new version generates all typed functions as a function with a length of two.  I was relying on the length being equal to the length of the signatures (or max of).  Was this a conscious breaking change?  Any reason we can no longer set the length to the max of the signature functions?

### PR DESCRIPTION
**Pull request by Hypercubed**
During typed-function creation, assign the max arguments length.

### CODE REVIEW

**Comment by harrysarson** [comment]
Any idea of the effect of this on performance?

**Comment by Hypercubed** [comment]
The length check is invoked when constructing the typed function.  It should have no impact on using the typed-function.

**Comment by josdejong** [comment]
Thanks @Hypercubed . I'm a bit in doubt whether this use case is generic enough to put it in the library. If needed, it's quite easy to write your own util function to calculate the maxLength of the arguments:

```js
function maxArgLength(typedFunction) {
  var signatures = Object.keys(typedFunction.signatures);
  var signatureLengths = signatures.map(function (signature) {
    return (signature.indexOf('...') !== -1) 
      ? Infinity 
      : signature.split(',').length;
  });

  return Math.max.apply(null, signatureLengths);
}
```



I would like to keep the library as lightweight as possible, so I propose we only implement this when it becomes an often requested feature.

**Comment by Hypercubed** [comment]
Understood... I'll respect your decision... of course... but:

1) This is a breaking change from v0
2) We might say the same for assigning the `name` and `signatures` property.  Both of which alter the function in a way that may cause de-optimization. *

\* I can't find the reference now, but assigning properties to a function changes it (in v8) from a native Function to a Function-like class.  There was a time (not sure if it's still true) that this causes serious deoptimizations.  If you are worried about perfomance of the generated typed function you might investigate storing these (`name`, `signatures`, etc) in something not attached to the function... maybe a WeakMap?

**Comment by josdejong** [comment]
Thanks for your input. I didn't know that assigning properties to a function can cause deoptimizations. 

What I did for v1 is set up a [benchmark in typed-function](https://github.com/josdejong/typed-function/blob/master/benchmark/benchmark.js), and additionally I've run benchmarks with [mathjs](https://mathjs.org) which uses `typed-function` at it's core. I tried out various concepts to see how they perform on Chrome, and Firefox, and node.js. It is worth to try out how much impact these function properties have. If it has a significant, negative impact we can consider alternative solutions.

**Comment by Hypercubed** [comment]
FYI... here is information on the function deopt... 

https://github.com/GoogleChrome/devtools-docs/issues/53#issuecomment-147569505

Almost 4 years old so YMMV.

**Comment by josdejong** [comment]
:+1: thanks for sharing! Curious to see how much impact this has in practice in `typed-function`.

**Pull request closed without merging**
